site_name: 'TerminalDrawer'
site_url: https://duvbolone.github.io/TerminalDrawer
repo_url: https://github.com/duvbolone/TerminalDrawer
site_description: 'TerminalDrawer Documentation'
site_author: 'Matt3o0'
theme:
  font:
    text: Roboto Mono
  name: 'material'
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - footer.prev_next
    - revision.date
    - revision.history

plugins:
  - git-revision-date

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: "#"
nav:
  - Home: index.md
  - Building: building.md
  - Modes: modes.md
  - Options: options.md
